### ISSUE TITLE
Request for access to repo so i can merge vault integration

### ISSUE THREAD

**Issue by skattoju4** [khos2ow/cloudstack#6]
Hey @khos2ow , could you give me access to this repo so i can continue on the vault integration pr ? Or do you suggest opening a new pr ?

**Comment by khos2ow** [comment]
Hey @skattoju4! I'd be happy to give you access, but it seems the original PR is already closed anyway and it might be better to open a new PR.

I'd suggest to make a comment in https://github.com/apache/cloudstack/pull/2850 and see if folks want to continue on the same PR or prefer a new one and we can take it from there.

**Comment by skattoju4** [comment]
They said to rebase and reopen so I figured we could continue on the same.. I don't mind creating a new one either..

**Comment by khos2ow** [comment]
Cool, I just sent you an invitation.

**Comment by skattoju4** [comment]
Thanks!

**Comment by skattoju4** [comment]
Thanks!

**Comment by khos2ow** [comment]
For sure, let me know if you need my help on anything. Although I still think you (or even me) cannot directly open up the closed PR, but for sure someone from the maintainer can. So have that in mind before going knee deep in rebasing!

**Comment by khos2ow** [comment]
That said, I took a quick look and rebasing this branch on current master is fairly straight forward and it only resulted in couple of conflicted files, so you should be, somewhat, good to go.
